root: "~/"

defaults:
  # File and directory permissions.
  # Empty values will not change permissions.
  fmode:
  dmode:

  # File and directory owner and group.
  # Empty values will not change ownership.
  owner:
  group:

  # Hosts to install this unit on.
  # Empty array will install on all hosts.
  hosts: []

  # Only install this unit if packages are present.
  # Empty array will not check for any packages.
  packages: []

config_files:
  - src: bashrc
    dst: .bashrc
    fmode: 0644

symlinks:
  - src: sublime/Packages/User
    dst: .config/sublime-text-3/Packages

  - src: sublime/Packages/User
    dst: Library/Application Support/Sublime Text 3/Packages
