right_format = """
$cmd_duration\
$status
"""

[character]
success_symbol = '[➜](bold green)'

[git_status]
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
format = '[$duration]($style)'
style = 'bold yellow'
min_time = 0
show_milliseconds = true
